name: Frontend CI/CD 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build App
        run: npm run build

      # Optional: Upload build artifacts (e.g., for Netlify/Vercel/Firebase)
      - name: Upload Production Build
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build
